name: build and test
on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
env:
  DOTNET_VERSION: "7.0.100-preview.1.22110.4"
  PROJECT: "./src/Services/Account/WorkerService"
  TEST: "./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests"
jobs:
  call-build-and-test:
    uses: ./.github/workflows/template-build-and-test.yaml
    with:
      sdk: ${{ env.DOTNET_VERSION }}
      project: ${{ env.PROJECT }}
      test: ${{ env.TEST }}