name: Account build and test

on:
  push:
    paths:
      - src/Services/Account/**.cs
      - src/Services/Account/**.csproj
      - Directory.Build.props

jobs:
  account-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      project: ./src/Services/Account/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests