name: build and test

on:
  workflow_call:
    inputs:
      name:
        description: 'The project name passed from the caller workflow'
        required: true
        type: string
      dotnet-version:
        description: 'The SKD version passed from the caller workflow'
        required: true
        type: string
      project:
        description: 'The *csproj project path passed from the caller workflow'
        required: true
        type: string
      test:
        description: 'The *csproj test path passed from the caller workflow'
        required: true
        type: string
        
jobs:
  build-and-test:
    name: build-and-test-${{ inputs.name }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: ./github/workflows/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ inputs.project }}
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ${{ inputs.test }}
        run: dotnet test --no-restore --verbosity normal