name: Catalog build and test

on:
  push:
    paths:
      - src/Services/Catalog/**.cs
      - src/Services/Catalog/**.csproj
      - Directory.Build.props

jobs:
  catalog-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      project: ./src/Services/Catalog/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests