name: catalog build and test
on:
  push:
#  pull_request:
#    branches: [ main ]
    paths:
      - ./src/Services/Catalog/**.cs
      - ./src/Services/Catalog/**.csproj
jobs:
  account-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      name: catalog
      dotnet-version: 7.0.100-preview.1.22110.4
      project: ./src/Services/Catalog/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests