name: Identity build and test

on:
  push:
    paths:
      - src/Services/Identity/**.cs
      - src/Services/Identity/**.csproj
      - Directory.Build.props

jobs:
  identity-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      project: ./src/Services/Identity/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests