name: build and test
on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
env:
  DOTNET_VERSION: 7.0.100-preview.1.22110.4
  PROJECT: src/Services/Identity/WorkerService
  TEST: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        working-directory: ${{ env.PROJECT }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ env.PROJECT }}
        run: dotnet build --configuration Release --no-restore
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Test
        working-directory: ${{ env.TEST }}
        run: dotnet test --no-restore --verbosity normal