name: Identity build and test

on:
  push:
    paths:
      - src/Services/Identity/**.cs
      - src/Services/Identity/**.csproj

jobs:
  identity-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      dotnet-version: 7.0.100-preview.1.22110.4
      project: ./src/Services/Identity/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests