name: Identity build and test
on:
  push:
    #  pull_request:
    #    branches: [ main ]
    paths:
      - ./src/Services/Identity/**.cs
      - ./src/Services/Identity/**.csproj
jobs:
  account-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      name: identity
      dotnet-version: 7.0.100-preview.1.22110.4
      project: ./src/Services/Identity/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests