name: build and test
on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
jobs:
  call-build-and-test:
    uses: ./.github/workflows/template-build-and-test.yaml
    with:
      sdk: 7.0.100-preview.1.22110.4
      project: ./src/Services/Order/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests