name: payment build and test

on:
  push:
    paths:
      - src/Services/Payment/**.cs
      - src/Services/Payment/**.csproj
jobs:
  account-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      dotnet-version: 7.0.100-preview.1.22110.4
      project: ./src/Services/Payment/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests