name: Payment build and test

on:
  push:
    paths:
      - src/Services/Payment/**.cs
      - src/Services/Payment/**.csproj
      - Directory.Build.props

jobs:
  payment-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      project: ./src/Services/Payment/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests