name: Setup .NET

inputs:
  dotnet-version:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}