name: Shopping Cart build and test

on:
  push:
    paths:
      - src/Services/ShoppingCart/**.cs
      - src/Services/ShoppingCart/**.csproj
      - Directory.Build.props

jobs:
  shoppingcart-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      project: ./src/Services/ShoppingCart/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests