name: build and test
on:
  workflow_call:
    inputs:
      sdk:
        required: true
      project:
        required: true
      test:
        required: true
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.sdk }}
      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ inputs.project }}
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ${{ inputs.test }}
        run: dotnet test --no-restore --verbosity normal