name: build and test

on:
  workflow_call:
    inputs:
      sdk:
        description: 'The SKD version passed from the caller workflow'
        required: true
        type: string
      project:
        description: 'The *csproj path passed from the caller workflow'
        required: true
        type: string
      test:
        description: 'The *csproj test path passed from the caller workflow'
        required: true
        type: string

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2 
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.sdk }}
      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run:  dotnet restore
      - name: Build
        working-directory: ${{ inputs.project }}
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ${{ inputs.test }}
        run: dotnet test --no-restore --verbosity normal
