name: Warehouse build and test

on:
  push:
    paths:
      - src/Services/Warehouse/**.cs
      - src/Services/Warehouse/**.csproj
      - Directory.Build.props

jobs:
  warehouse-build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      project: ./src/Services/Warehouse/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests